### ISSUE TITLE
Links are dead

### ISSUE THREAD

**Issue by Berovowilare** [rBiblia/rbiblia-web#12]
Hello

All links to https://rbiblia.toborek.info/donation/ and contact etc.  seems to be dead.

Fatal error: Uncaught TypeError: Cannot assign bool to property Clash82Include\CounterController::$long of type int in /home/omni/domains/include/bricks/CounterController.php:313 Stack trace: #0 /home/omni/domains/include/wrappers/counter.php(68): Clash82Include\CounterController->__construct('rbiblia', '208.54.104.184,...', Object(Clash82Include\DatabaseClient), Object(Clash82Include\CookiesManager), Object(Clash82Include\GeoClient), Array, Array, Array) #1 /home/omni/domains/include/wrappers/counter.php(35): counter::getCounter('rbiblia') #2 /home/omni/domains/rbiblia.toborek.info/public_html/index.php(19): counter::increment('rbiblia') #3 /home/omni/domains/rbiblia.toborek.info/public_html/index.php(130): rBibliaWebpage->__construct() #4 {main} thrown in /home/omni/domains/include/bricks/CounterController.php on line 313

**Comment by clash82** [comment]
It's not related to the project... this is thrown by one of my helper scripts on the server. I added corresponding patch which should fix issues like those in the future. Let me know if you still cannot access any of those pages, please.
